apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  namespace: stribble-bc-svc
  labels:
    app: jenkins
spec:
  containers:
  - name: jenkins
    image: jenkins/jenkins
    ports:
    - containerPort: 8080