apiVersion: v1
kind: Service
metadata:
  name: load-balancer-service
  namespace: stribble-bc-svc
spec:
  selector:
    app: jenkins
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer